## PBS configure 
#PBS -N RNA-seq-3
#PBS -j oe
#PBS -q batch
#PBS -S /bin/sh
#PBS -l nodes=1:ppn=18
#PBS -l mem=20G


samtools view -S /md01/lixh/HOTAIR/RNA-seq/Map/OE-YTHDF3-5-2.sam -b > /md01/lixh/HOTAIR/RNA-seq/Map/OE-YTHDF3-5-2.bam

samtools view -S /md01/lixh/HOTAIR/RNA-seq/Map/OE-YTHDF3-5-1.sam -b > /md01/lixh/HOTAIR/RNA-seq/Map/OE-YTHDF3-5-1.bam

samtools view -S /md01/lixh/HOTAIR/RNA-seq/Map/OE-YTHDF3-4-2.sam -b > /md01/lixh/HOTAIR/RNA-seq/Map/OE-YTHDF3-4-2.bam

samtools view -S /md01/lixh/HOTAIR/RNA-seq/Map/OE-YTHDF3-4-1.sam -b > /md01/lixh/HOTAIR/RNA-seq/Map/OE-YTHDF3-4-1.bam
 
samtools view -S /md01/lixh/HOTAIR/RNA-seq/Map/OE-YTHDF3-2-2.sam -b > /md01/lixh/HOTAIR/RNA-seq/Map/OE-YTHDF3-2-2.bam

samtools view -S /md01/lixh/HOTAIR/RNA-seq/Map/OE-YTHDF3-2-1.sam -b > /md01/lixh/HOTAIR/RNA-seq/Map/OE-YTHDF3-2-1.bam

samtools view -S /md01/lixh/HOTAIR/RNA-seq/Map/OE-YTHDF3-1-2.sam -b > /md01/lixh/HOTAIR/RNA-seq/Map/OE-YTHDF3-1-2.bam

samtools view -S /md01/lixh/HOTAIR/RNA-seq/Map/OE-YTHDF3-1-1.sam -b > /md01/lixh/HOTAIR/RNA-seq/Map/OE-YTHDF3-1-1.bam

samtools view -S /md01/lixh/HOTAIR/RNA-seq/Map/OE-puro-3-2.sam -b > /md01/lixh/HOTAIR/RNA-seq/Map/OE-puro-3-2.bam

samtools view -S /md01/lixh/HOTAIR/RNA-seq/Map/OE-puro-3-1.sam -b > /md01/lixh/HOTAIR/RNA-seq/Map/OE-puro-3-1.bam

samtools view -S /md01/lixh/HOTAIR/RNA-seq/Map/OE-P18-2.sam -b > /md01/lixh/HOTAIR/RNA-seq/Map/OE-P18-2.bam

samtools view -S /md01/lixh/HOTAIR/RNA-seq/Map/OE-P18-1.sam -b > /md01/lixh/HOTAIR/RNA-seq/Map/OE-P18-1.bam

samtools view -S /md01/lixh/HOTAIR/RNA-seq/Map/C-YTHDF3-4-2.sam -b > /md01/lixh/HOTAIR/RNA-seq/Map/C-YTHDF3-4-2.bam

samtools view -S /md01/lixh/HOTAIR/RNA-seq/Map/C-YTHDF3-4-1.sam -b > /md01/lixh/HOTAIR/RNA-seq/Map/C-YTHDF3-4-1.bam

samtools view -S /md01/lixh/HOTAIR/RNA-seq/Map/C-YTHDF3-2-2.sam -b > /md01/lixh/HOTAIR/RNA-seq/Map/C-YTHDF3-2-2.bam

samtools view -S /md01/lixh/HOTAIR/RNA-seq/Map/C-YTHDF3-2-1.sam -b > /md01/lixh/HOTAIR/RNA-seq/Map/C-YTHDF3-2-1.bam

samtools view -S /md01/lixh/HOTAIR/RNA-seq/Map/C-puro-8-1.sam -b > /md01/lixh/HOTAIR/RNA-seq/Map/C-puro-8-1.bam

samtools view -S /md01/lixh/HOTAIR/RNA-seq/Map/C-puro-8-2.sam -b > /md01/lixh/HOTAIR/RNA-seq/Map/C-puro-8-2.bam

samtools view -S /md01/lixh/HOTAIR/RNA-seq/Map/C-P18-2.sam -b > /md01/lixh/HOTAIR/RNA-seq/Map/C-P18-2.bam

samtools view -S /md01/lixh/HOTAIR/RNA-seq/Map/C-P18-1.sam -b > /md01/lixh/HOTAIR/RNA-seq/Map/C-P18-1.bam

samtools view -S /md01/lixh/HOTAIR/RNA-seq/Map/C-NT-1-1-2.sam -b > /md01/lixh/HOTAIR/RNA-seq/Map/C-NT-1-1-2.bam

samtools view -S /md01/lixh/HOTAIR/RNA-seq/Map/C-NT-1-1-1.sam -b > /md01/lixh/HOTAIR/RNA-seq/Map/C-NT-1-1-1.bam



