## PBS configure 
#PBS -N RNA-seq-2
#PBS -j oe
#PBS -q batch
#PBS -S /bin/sh
#PBS -l nodes=1:ppn=18
#PBS -l mem=20G



/md01/lixh/software/hisat2-2.2.1/hisat2 -t -p 8 -x /md01/lixh/HOTAIR/RNA-seq/Ref/hg19/genome -1 /md01/lixh/HOTAIR/RNA-seq/Trim/OE-YTHDF3-5-2_1_paired.fq.gz -2 /md01/lixh/HOTAIR/RNA-seq/Trim/OE-YTHDF3-5-2_2_paired.fq.gz -S /md01/lixh/HOTAIR/RNA-seq/Map/OE-YTHDF3-5-2.sam


/md01/lixh/software/hisat2-2.2.1/hisat2 -t -p 8 -x /md01/lixh/HOTAIR/RNA-seq/Ref/hg19/genome -1 /md01/lixh/HOTAIR/RNA-seq/Trim/OE-YTHDF3-5-1_1_paired.fq.gz -2 /md01/lixh/HOTAIR/RNA-seq/Trim/OE-YTHDF3-5-1_2_paired.fq.gz -S /md01/lixh/HOTAIR/RNA-seq/Map/OE-YTHDF3-5-1.sam


/md01/lixh/software/hisat2-2.2.1/hisat2 -t -p 8 -x /md01/lixh/HOTAIR/RNA-seq/Ref/hg19/genome -1 /md01/lixh/HOTAIR/RNA-seq/Trim/OE-YTHDF3-4-2_1_paired.fq.gz -2 /md01/lixh/HOTAIR/RNA-seq/Trim/OE-YTHDF3-4-2_2_paired.fq.gz -S /md01/lixh/HOTAIR/RNA-seq/Map/OE-YTHDF3-4-2.sam


/md01/lixh/software/hisat2-2.2.1/hisat2 -t -p 8 -x /md01/lixh/HOTAIR/RNA-seq/Ref/hg19/genome -1 /md01/lixh/HOTAIR/RNA-seq/Trim/OE-YTHDF3-4-1_1_paired.fq.gz -2 /md01/lixh/HOTAIR/RNA-seq/Trim/OE-YTHDF3-4-1_2_paired.fq.gz -S /md01/lixh/HOTAIR/RNA-seq/Map/OE-YTHDF3-4-1.sam


/md01/lixh/software/hisat2-2.2.1/hisat2 -t -p 8 -x /md01/lixh/HOTAIR/RNA-seq/Ref/hg19/genome -1 /md01/lixh/HOTAIR/RNA-seq/Trim/OE-YTHDF3-2-2_1_paired.fq.gz -2 /md01/lixh/HOTAIR/RNA-seq/Trim/OE-YTHDF3-2-2_2_paired.fq.gz -S /md01/lixh/HOTAIR/RNA-seq/Map/OE-YTHDF3-2-2.sam


/md01/lixh/software/hisat2-2.2.1/hisat2 -t -p 8 -x /md01/lixh/HOTAIR/RNA-seq/Ref/hg19/genome -1 /md01/lixh/HOTAIR/RNA-seq/Trim/OE-YTHDF3-2-1_1_paired.fq.gz -2 /md01/lixh/HOTAIR/RNA-seq/Trim/OE-YTHDF3-2-1_2_paired.fq.gz -S /md01/lixh/HOTAIR/RNA-seq/Map/OE-YTHDF3-2-1.sam

/md01/lixh/software/hisat2-2.2.1/hisat2 -t -p 8 -x /md01/lixh/HOTAIR/RNA-seq/Ref/hg19/genome -1 /md01/lixh/HOTAIR/RNA-seq/Trim/OE-YTHDF3-1-2_1_paired.fq.gz -2 /md01/lixh/HOTAIR/RNA-seq/Trim/OE-YTHDF3-1-2_2_paired.fq.gz -S /md01/lixh/HOTAIR/RNA-seq/Map/OE-YTHDF3-1-2.sam


/md01/lixh/software/hisat2-2.2.1/hisat2 -t -p 8 -x /md01/lixh/HOTAIR/RNA-seq/Ref/hg19/genome -1 /md01/lixh/HOTAIR/RNA-seq/Trim/OE-YTHDF3-1-1_1_paired.fq.gz -2 /md01/lixh/HOTAIR/RNA-seq/Trim/OE-YTHDF3-1-1_2_paired.fq.gz -S /md01/lixh/HOTAIR/RNA-seq/Map/OE-YTHDF3-1-1.sam


/md01/lixh/software/hisat2-2.2.1/hisat2 -t -p 8 -x /md01/lixh/HOTAIR/RNA-seq/Ref/hg19/genome -1 /md01/lixh/HOTAIR/RNA-seq/Trim/OE-puro-3-2_1_paired.fq.gz -2 /md01/lixh/HOTAIR/RNA-seq/Trim/OE-puro-3-2_2_paired.fq.gz -S /md01/lixh/HOTAIR/RNA-seq/Map/OE-puro-3-2.sam


/md01/lixh/software/hisat2-2.2.1/hisat2 -t -p 8 -x /md01/lixh/HOTAIR/RNA-seq/Ref/hg19/genome -1 /md01/lixh/HOTAIR/RNA-seq/Trim/OE-puro-3-1_1_paired.fq.gz -2 /md01/lixh/HOTAIR/RNA-seq/Trim/OE-puro-3-1_2_paired.fq.gz -S /md01/lixh/HOTAIR/RNA-seq/Map/OE-puro-3-1.sam

/md01/lixh/software/hisat2-2.2.1/hisat2 -t -p 8 -x /md01/lixh/HOTAIR/RNA-seq/Ref/hg19/genome -1 /md01/lixh/HOTAIR/RNA-seq/Trim/OE-P18-2_1_paired.fq.gz -2 /md01/lixh/HOTAIR/RNA-seq/Trim/OE-P18-2_2_paired.fq.gz -S /md01/lixh/HOTAIR/RNA-seq/Map/OE-P18-2.sam


/md01/lixh/software/hisat2-2.2.1/hisat2 -t -p 8 -x /md01/lixh/HOTAIR/RNA-seq/Ref/hg19/genome -1 /md01/lixh/HOTAIR/RNA-seq/Trim/OE-P18-1_1_paired.fq.gz -2 /md01/lixh/HOTAIR/RNA-seq/Trim/OE-P18-1_2_paired.fq.gz -S /md01/lixh/HOTAIR/RNA-seq/Map/OE-P18-1.sam


/md01/lixh/software/hisat2-2.2.1/hisat2 -t -p 8 -x /md01/lixh/HOTAIR/RNA-seq/Ref/hg19/genome -1 /md01/lixh/HOTAIR/RNA-seq/Trim/C-YTHDF3-4-2_1_paired.fq.gz -2 /md01/lixh/HOTAIR/RNA-seq/Trim/C-YTHDF3-4-2_2_paired.fq.gz -S /md01/lixh/HOTAIR/RNA-seq/Map/C-YTHDF3-4-2.sam


/md01/lixh/software/hisat2-2.2.1/hisat2 -t -p 8 -x /md01/lixh/HOTAIR/RNA-seq/Ref/hg19/genome -1 /md01/lixh/HOTAIR/RNA-seq/Trim/C-YTHDF3-4-1_1_paired.fq.gz -2 /md01/lixh/HOTAIR/RNA-seq/Trim/C-YTHDF3-4-1_2_paired.fq.gz -S /md01/lixh/HOTAIR/RNA-seq/Map/C-YTHDF3-4-1.sam


/md01/lixh/software/hisat2-2.2.1/hisat2 -t -p 8 -x /md01/lixh/HOTAIR/RNA-seq/Ref/hg19/genome -1 /md01/lixh/HOTAIR/RNA-seq/Trim/C-YTHDF3-2-2_1_paired.fq.gz -2 /md01/lixh/HOTAIR/RNA-seq/Trim/C-YTHDF3-2-2_2_paired.fq.gz -S /md01/lixh/HOTAIR/RNA-seq/Map/C-YTHDF3-2-2.sam


/md01/lixh/software/hisat2-2.2.1/hisat2 -t -p 8 -x /md01/lixh/HOTAIR/RNA-seq/Ref/hg19/genome -1 /md01/lixh/HOTAIR/RNA-seq/Trim/C-YTHDF3-2-1_1_paired.fq.gz -2 /md01/lixh/HOTAIR/RNA-seq/Trim/C-YTHDF3-2-1_2_paired.fq.gz -S /md01/lixh/HOTAIR/RNA-seq/Map/C-YTHDF3-2-1.sam

/md01/lixh/software/hisat2-2.2.1/hisat2 -t -p 8 -x /md01/lixh/HOTAIR/RNA-seq/Ref/hg19/genome -1 /md01/lixh/HOTAIR/RNA-seq/Trim/C-puro-8-1_1_paired.fq.gz -2 /md01/lixh/HOTAIR/RNA-seq/Trim/C-puro-8-1_2_paired.fq.gz -S /md01/lixh/HOTAIR/RNA-seq/Map/C-puro-8-1.sam

/md01/lixh/software/hisat2-2.2.1/hisat2 -t -p 8 -x /md01/lixh/HOTAIR/RNA-seq/Ref/hg19/genome -1 /md01/lixh/HOTAIR/RNA-seq/Trim/C-puro-8-2_1_paired.fq.gz -2 /md01/lixh/HOTAIR/RNA-seq/Trim/C-puro-8-2_2_paired.fq.gz -S /md01/lixh/HOTAIR/RNA-seq/Map/C-puro-8-2.sam

/md01/lixh/software/hisat2-2.2.1/hisat2 -t -p 8 -x /md01/lixh/HOTAIR/RNA-seq/Ref/hg19/genome -1 /md01/lixh/HOTAIR/RNA-seq/Trim/C-P18-2_1_paired.fq.gz -2 /md01/lixh/HOTAIR/RNA-seq/Trim/C-P18-2_2_paired.fq.gz -S /md01/lixh/HOTAIR/RNA-seq/Map/C-P18-2.sam

/md01/lixh/software/hisat2-2.2.1/hisat2 -t -p 8 -x /md01/lixh/HOTAIR/RNA-seq/Ref/hg19/genome -1 /md01/lixh/HOTAIR/RNA-seq/Trim/C-P18-1_1_paired.fq.gz -2 /md01/lixh/HOTAIR/RNA-seq/Trim/C-P18-1_2_paired.fq.gz -S /md01/lixh/HOTAIR/RNA-seq/Map/C-P18-1.sam

/md01/lixh/software/hisat2-2.2.1/hisat2 -t -p 8 -x /md01/lixh/HOTAIR/RNA-seq/Ref/hg19/genome -1 /md01/lixh/HOTAIR/RNA-seq/Trim/C-NT-1-1-2_1_paired.fq.gz -2 /md01/lixh/HOTAIR/RNA-seq/Trim/C-NT-1-1-2_2_paired.fq.gz -S /md01/lixh/HOTAIR/RNA-seq/Map/C-NT-1-1-2.sam

/md01/lixh/software/hisat2-2.2.1/hisat2 -t -p 8 -x /md01/lixh/HOTAIR/RNA-seq/Ref/hg19/genome -1 /md01/lixh/HOTAIR/RNA-seq/Trim/C-NT-1-1-1_1_paired.fq.gz -2 /md01/lixh/HOTAIR/RNA-seq/Trim/C-NT-1-1-1_2_paired.fq.gz -S /md01/lixh/HOTAIR/RNA-seq/Map/C-NT-1-1-1.sam




